const LESSONS = [
  {
    id: "in-world",
    witness: "john-17-16",
    title: "In the world, not of it",
    teach: "You are not asked to leave the street. You are asked not to belong to it. The world may have your work and your courtesy. It does not get your mind, your fear, or your worship.",
    keep: "Do the next honest task. Do not feed the crowd's mood.",
    close: "Where did you belong to the world today, and where did you refuse?",
    pt: {
      title: "No mundo, não do mundo",
      teach: "Não pedem que você saia da rua. Pedem que você não pertença a ela. O mundo pode ter o seu trabalho e a sua cortesia. Não fica com a sua mente, o seu medo, nem a sua adoração.",
      keep: "Faça a próxima tarefa honesta. Não alimente o humor da turba.",
      close: "Onde você pertenceu ao mundo hoje, e onde recusou?",
    },
  },
  {
    id: "faith-over-opinion",
    witness: "cor-2-5",
    title: "Faith over opinion",
    teach: "Opinion is cheap and loud. Faith is a weight you carry when you cannot see the end. Do not confuse having a take with having a foundation.",
    keep: "If a remark only displays you, do not make it.",
    close: "Did you trust God, or did you trust a take?",
    pt: {
      title: "Fé acima da opinião",
      teach: "Opinião é barata e alta. Fé é um peso que você carrega quando não vê o fim. Não confunda ter um palpite com ter fundamento.",
      keep: "Se um comentário só o exibe, não o faça.",
      close: "Você confiou em Deus, ou num palpite?",
    },
  },
  {
    id: "inner-citadel",
    witness: "aur-retire",
    title: "The inner citadel",
    teach: "A change of landscape does not save you if the mind is still a market. You can go into yourself at the table, in the queue, in the noise. That room is yours.",
    keep: "Once today, stop. Enter that room for one minute before you answer anyone.",
    close: "Did you have a place inside that the day could not enter?",
    pt: {
      title: "A cidadela interior",
      teach: "Mudar de paisagem não salva se a mente continua um mercado. Você pode recolher-se à mesa, na fila, no barulho. Esse quarto é seu.",
      keep: "Uma vez hoje, pare. Entre nesse quarto por um minuto antes de responder a alguém.",
      close: "Você teve um lugar dentro que o dia não pôde entrar?",
    },
  },
  {
    id: "crowd-untruth",
    witness: "kierkegaard-crowd",
    title: "The crowd is untruth",
    teach: "A crowd can be right about a fact and still be untrue as a way of living. Truth needs a person who will stand when the room moves. Solitude is how a word stays a word.",
    keep: "Do not let a group finish your sentence.",
    close: "Whose voice did you borrow today?",
    pt: {
      title: "A multidão é a inverdade",
      teach: "Uma multidão pode acertar um fato e ainda ser falsa como modo de viver. A verdade precisa de alguém que fique quando a sala se move. A solidão é como uma palavra continua palavra.",
      keep: "Não deixe um grupo terminar a sua frase.",
      close: "De quem você tomou emprestada a voz hoje?",
    },
  },
  {
    id: "own-burden",
    witness: "gal-6-5",
    title: "Bear your own burden",
    teach: "Help is real. So is the load that is yours alone. Do not outsource your courage, your prayer, or today's work to someone else's mood. Support that replaces your spine is not love.",
    keep: "Finish one hard thing without asking anyone to feel it with you.",
    close: "What did you carry yourself, and what did you hand off too soon?",
    pt: {
      title: "Leve a sua própria carga",
      teach: "Ajuda é real. Também é real o peso que só você pode levar. Não terceirize a coragem, a oração ou o trabalho do dia para o humor de outra pessoa. Apoio que substitui a sua espinha não é amor.",
      keep: "Termine uma coisa difícil sem pedir que alguém a sinta com você.",
      close: "O que você carregou sozinho, e o que entregou cedo demais?",
    },
  },
  {
    id: "quiet-confidence",
    witness: "isa-30-15",
    title: "Quietness and confidence",
    teach: "Strength here is not volume. It is returning, resting, refusing the panic that wants a speech. Power sits in a settled trust, not in the next argument.",
    keep: "When the itch to comment comes, be still instead.",
    close: "Was your strength quiet, or did you spend it on noise?",
    pt: {
      title: "Sossego e confiança",
      teach: "A força aqui não é volume. É voltar, descansar, recusar o pânico que quer um discurso. O poder mora numa confiança quieta, não no próximo argumento.",
      keep: "Quando vier a coceira de comentar, fique quieto.",
      close: "A sua força foi quieta, ou você a gastou no barulho?",
    },
  },
  {
    id: "keep-course",
    witness: "luke-9-62",
    title: "Keep the course",
    teach: "Looking back is how a furrow goes crooked. The kingdom is not for the man who starts and then hunts yesterday's crowd for a verdict. Hand on the plough. Eyes forward.",
    keep: "Do not reopen a finished decision to please a room.",
    close: "Where did you look back?",
    pt: {
      title: "Mantenha o rumo",
      teach: "Olhar para trás é como o sulco entorta. O reino não é de quem começa e depois caça o veredito da turba de ontem. Mão no arado. Olhos à frente.",
      keep: "Não reabra uma decisão pronta para agradar uma sala.",
      close: "Onde você olhou para trás?",
    },
  },
  {
    id: "still-alone",
    witness: "pascal-room",
    title: "Still, even alone",
    teach: "We fill the hour with other people so we will not meet ourselves. The ark is first a quiet house, even if only one soul is awake in it.",
    keep: "Take ten minutes without a screen. Do not fill them.",
    close: "Could you be alone without fleeing?",
    pt: {
      title: "Quietos, mesmo sós",
      teach: "Enchemos a hora com outras pessoas para não nos encontrarmos. A arca é primeiro uma casa quieta, mesmo que só uma alma esteja acordada nela.",
      keep: "Tire dez minutos sem tela. Não os preencha.",
      close: "Você conseguiu estar só sem fugir?",
    },
  },
  {
    id: "treasure",
    witness: "matt-6-21",
    title: "Where the treasure is",
    teach: "The heart follows what you store. If you store outrage, news, and other men's praise, that is where you will live. Store the kingdom, and the heart comes with it.",
    keep: "Do not save what you do not want to love.",
    close: "What did you store today?",
    pt: {
      title: "Onde está o tesouro",
      teach: "O coração segue o que você guarda. Se guarda revolta, notícia e o louvor dos outros, é ali que você vai morar. Guarde o reino, e o coração vem junto.",
      keep: "Não guarde o que você não quer amar.",
      close: "O que você guardou hoje?",
    },
  },
  {
    id: "sufficient-day",
    witness: "matt-6-34",
    title: "Sufficient unto the day",
    teach: "Tomorrow is a thief. It steals the duty that is in your hands. The evil of today is enough. You are not required to rehearse next week's flood.",
    keep: "When the mind runs ahead, bring it back to this hour's work.",
    close: "Did you live this day, or a day that has not come?",
    pt: {
      title: "Basta a cada dia o seu mal",
      teach: "Amanhã é ladrão. Rouba o dever que está nas suas mãos. O mal de hoje basta. Você não é obrigado a ensaiar o dilúvio da semana que vem.",
      keep: "Quando a mente disparar à frente, traga-a de volta ao trabalho desta hora.",
      close: "Você viveu este dia, ou um dia que ainda não veio?",
    },
  },
  {
    id: "live-not-lie",
    witness: "solz-lie",
    title: "Not through me",
    teach: "You may not stop the lie from entering the world. You can refuse to be its mouth. That is a whole politics for a private man: no share in the false word, even when the false word wins.",
    keep: "Do not repeat a sentence you do not know to be true.",
    close: "Did any lie pass through you?",
    pt: {
      title: "Não por mim",
      teach: "Você pode não impedir a mentira de entrar no mundo. Pode recusar ser a boca dela. Isso já é uma política inteira para um homem privado: nenhuma parte na palavra falsa, mesmo quando ela vence.",
      keep: "Não repita uma frase que você não sabe ser verdadeira.",
      close: "Alguma mentira passou por você?",
    },
  },
  {
    id: "aim-heaven",
    witness: "lewis-aim",
    title: "Aim at heaven",
    teach: "Aim at earth and you lose earth too. The one who wants God first is not less useful in the house. He is the only one who can keep a house without making it an idol.",
    keep: "Before a choice, ask what you are aiming at.",
    close: "What did you aim at?",
    pt: {
      title: "Mire o céu",
      teach: "Mire a terra e perde a terra também. Quem quer Deus primeiro não é menos útil em casa. É o único que consegue guardar uma casa sem transformá-la em ídolo.",
      keep: "Antes de uma escolha, pergunte no que você está mirando.",
      close: "No que você mirou?",
    },
  },
  {
    id: "noah-built",
    witness: "heb-11-7",
    title: "He built",
    teach: "Noah did not drain the flood. He was warned of things not seen, and he built. The ark is not a comment on the weather. It is timber, day after day, while the street still eats and marries and does not know.",
    keep: "Build something that will still stand if the noise is right or wrong.",
    close: "What did you build, and what did you only talk about?",
    pt: {
      title: "Ele construiu",
      teach: "Noé não esgotou o dilúvio. Foi avisado do que ainda não se via, e construiu. A arca não é um comentário sobre o tempo. É madeira, dia após dia, enquanto a rua ainda come, casa, e não sabe.",
      keep: "Construa algo que continue de pé, certo ou errado o barulho.",
      close: "O que você construiu, e o que só comentou?",
    },
  },
  {
    id: "nothing-disturb",
    witness: "teresa-nada",
    title: "Let nothing disturb you",
    teach: "This does not mean you will feel nothing. It means God does not change when your feelings do. Patience obtains. Whoever has God lacks nothing. The rest is weather.",
    keep: "Name one disturbance. Do not obey it.",
    close: "What disturbed you, and did you let it rule?",
    pt: {
      title: "Nada te turbe",
      teach: "Isso não quer dizer que você não vai sentir. Quer dizer que Deus não muda quando os seus sentimentos mudam. A paciência alcança. Quem tem Deus, nada lhe falta. O resto é tempo.",
      keep: "Nomeie um distúrbio. Não o obedeça.",
      close: "O que o turbou, e você deixou isso mandar?",
    },
  },
  {
    id: "heart-restless",
    witness: "augustine-rest",
    title: "Restless until it rests",
    teach: "The restlessness is not a defect to be medicated by more company. It is a compass. You were made for God. Until the heart rests there, every other rest will leak.",
    keep: "Do not treat unease as a problem to scroll away.",
    close: "Where did you try to rest besides God?",
    pt: {
      title: "Inquieto até descansar",
      teach: "A inquietação não é defeito para medicar com mais companhia. É bússola. Você foi feito para Deus. Enquanto o coração não descansa nele, qualquer outro descanso vaza.",
      keep: "Não trate o desassossego como um problema para resolver rolando a tela.",
      close: "Onde você tentou descansar além de Deus?",
    },
  },
  {
    id: "not-conformed",
    witness: "rom-12-2",
    title: "Do not be conformed",
    teach: "The world has a mould. It is not only vice. It is the shape of the hour: what to fear, what to mock, what to repeat. Transformation starts in the mind, by renewal, not by a better costume.",
    keep: "Notice one way the day tried to mould you. Step out of it.",
    close: "Where did you take the world's shape?",
    pt: {
      title: "Não se conforme",
      teach: "O mundo tem um molde. Não é só o vício. É a forma da hora: o que temer, o que zombar, o que repetir. A transformação começa na mente, pela renovação, não por uma roupa melhor.",
      keep: "Note uma forma em que o dia tentou moldá-lo. Saia dela.",
      close: "Onde você tomou a forma do mundo?",
    },
  },
  {
    id: "views-not-things",
    witness: "epi-views",
    title: "Not the thing, the view",
    teach: "You are not required to be wrecked by what happens. The judgment you add is the hook. You can drop it now.",
    keep: "Once, when something stings, say: this is a view. Then choose.",
    close: "What view did you mistake for a fact?",
    pt: {
      title: "Não a coisa, o juízo",
      teach: "Você não é obrigado a naufragar no que acontece. O juízo que você acrescenta é o anzol. Pode soltá-lo agora.",
      keep: "Uma vez, quando algo doer, diga: isto é um juízo. Depois escolha.",
      close: "Que juízo você tomou por fato?",
    },
  },
  {
    id: "fear-of-man",
    witness: "prov-29-25",
    title: "The snare",
    teach: "Fear of man is a trap with a familiar bait: being thought well of. Trust in the Lord is not a mood. It is refusing that bait when the room goes quiet and waits for you to join.",
    keep: "Do not adjust your face to a face.",
    close: "Whom did you fear?",
    pt: {
      title: "O laço",
      teach: "O temor do homem é armadilha com isca conhecida: ser bem pensado. Confiar no Senhor não é um humor. É recusar essa isca quando a sala cala e espera que você entre.",
      keep: "Não ajuste o rosto a um rosto.",
      close: "De quem você teve medo?",
    },
  },
  {
    id: "promontory",
    witness: "aur-promontory",
    title: "The promontory",
    teach: "The waves are not a failure of the rock. They are what the sea does. Stand. The fury spends itself on you and becomes water again. You are not required to become the storm in order to survive it.",
    keep: "Do not match the day's agitation with your own.",
    close: "Did you stand, or did you churn?",
    pt: {
      title: "O promontório",
      teach: "As ondas não são falha da rocha. São o que o mar faz. Fique. A fúria se gasta em você e volta a ser água. Você não precisa virar a tempestade para sobreviver a ela.",
      keep: "Não responda à agitação do dia com a sua.",
      close: "Você ficou, ou se agitou?",
    },
  },
  {
    id: "be-still",
    witness: "ps-46-10",
    title: "Be still",
    teach: "Stillness is not emptiness. It is how you know that He is God and you are not the news. The command is first to the body that wants to manage the flood.",
    keep: "Before you speak of God, be still before Him.",
    close: "Were you still, even once?",
    pt: {
      title: "Aquietai-vos",
      teach: "Quietude não é vazio. É como você sabe que Ele é Deus e você não é o noticiário. O mandamento é primeiro ao corpo que quer administrar o dilúvio.",
      keep: "Antes de falar de Deus, aquiete-se diante dEle.",
      close: "Você esteve quieto, ao menos uma vez?",
    },
  },
  {
    id: "last-freedom",
    witness: "frankl-attitude",
    title: "The last freedom",
    teach: "One thing cannot be taken: the stance of the soul. Circumstance is not the last word. Attitude is a kind of prayer you can still make.",
    keep: "Choose the stance. Do not wait to feel it first.",
    close: "What attitude did you choose when you could not choose the facts?",
    pt: {
      title: "A última liberdade",
      teach: "Uma coisa não se tira: a postura da alma. A circunstância não é a última palavra. A atitude é uma oração que você ainda pode fazer.",
      keep: "Escolha a postura. Não espere senti-la primeiro.",
      close: "Que atitude você escolheu quando não pôde escolher os fatos?",
    },
  },
  {
    id: "one-thing",
    witness: "luke-10-42",
    title: "One thing is needful",
    teach: "Martha is not wicked. She is divided. Many things, all of them plausible. You can be busy in the house and absent from the one thing. Sit first. Then serve.",
    keep: "Do the needful thing before the many things.",
    close: "What many things owned you?",
    pt: {
      title: "Uma só é necessária",
      teach: "Marta não é má. Está dividida. Muitas coisas, todas plausíveis. Você pode estar ocupado em casa e ausente da única coisa. Sente-se primeiro. Depois sirva.",
      keep: "Faça o necessário antes das muitas coisas.",
      close: "Que muitas coisas o possuíram?",
    },
  },
  {
    id: "narrow-way",
    witness: "matt-7-14",
    title: "The narrow way",
    teach: "The wide gate is popular because it costs nothing up front. The narrow way is not cruelty. It is how a life stays a life. Few find it because few want a gate that small.",
    keep: "Take the smaller, truer option once today.",
    close: "Which gate did you use?",
    pt: {
      title: "O caminho estreito",
      teach: "A porta larga é popular porque não custa nada no começo. O caminho estreito não é crueldade. É como uma vida continua vida. Poucos o acham porque poucos querem uma porta tão pequena.",
      keep: "Uma vez hoje, escolha a opção menor e mais verdadeira.",
      close: "Por qual porta você entrou?",
    },
  },
  {
    id: "press-the-mark",
    witness: "phil-3-14",
    title: "Press toward the mark",
    teach: "Forgetting what is behind is not amnesia. It is refusing to live in the old race. The prize is ahead. A man looking over his shoulder cannot run.",
    keep: "Do not replay yesterday's argument. Run today's length.",
    close: "What from behind still had you?",
    pt: {
      title: "Prossiga para o alvo",
      teach: "Esquecer o que fica atrás não é amnésia. É recusar viver na corrida antiga. O prêmio está adiante. Quem olha por cima do ombro não corre.",
      keep: "Não recrie a briga de ontem. Corra o trecho de hoje.",
      close: "O que de trás ainda o tinha?",
    },
  },
  {
    id: "dyed-soul",
    witness: "aur-dye",
    title: "The colour of the thoughts",
    teach: "The soul takes the dye you soak it in. A day of other men's heat will colour you without your consent if you leave the vat open. Think on what is true, and the cloth changes.",
    keep: "Close one vat that stains you.",
    close: "What colour was the mind tonight?",
    pt: {
      title: "A cor dos pensamentos",
      teach: "A alma se tinge do que você a mergulha. Um dia no calor dos outros vai colorir você sem consentimento se o tanque ficar aberto. Pense no que é verdadeiro, e o pano muda.",
      keep: "Feche um tanque que o mancha.",
      close: "De que cor estava a mente esta noite?",
    },
  },
  {
    id: "better-to-trust",
    witness: "ps-118-8",
    title: "Better to trust in the Lord",
    teach: "Confidence in man is a habit of the forum. It feels like prudence. Scripture calls it a lesser bet. The Lord does not swell and vanish with a crowd.",
    keep: "Take one fear about people and set it down before God.",
    close: "In whom did you actually trust?",
    pt: {
      title: "Melhor confiar no Senhor",
      teach: "Confiar no homem é hábito do fórum. Parece prudência. A escritura chama isso de aposta menor. O Senhor não incha e some com a turba.",
      keep: "Pegue um medo das pessoas e coloque-o diante de Deus.",
      close: "Em quem você de fato confiou?",
    },
  },
  {
    id: "sound-mind",
    witness: "tim-1-7",
    title: "A sound mind",
    teach: "God has not given a spirit of fear. Power, love, and a sound mind — a held centre. Panic is not humility. It is unbelief with a loud pulse.",
    keep: "When fear speaks, answer with the next clear duty.",
    close: "Did you receive fear as if it were from God?",
    pt: {
      title: "Mente sóbria",
      teach: "Deus não nos deu espírito de temor. Fortaleza, amor e moderação — um centro firme. Pânico não é humildade. É incredulidade com pulso alto.",
      keep: "Quando o medo falar, responda com o próximo dever claro.",
      close: "Você recebeu o medo como se viesse de Deus?",
    },
  },
  {
    id: "finished-the-course",
    witness: "tim-4-7",
    title: "Keep the faith",
    teach: "The good fight is not won by a mood. It is finished. A course has a last mile. I kept the faith: a whole life in four words, and it is still available today.",
    keep: "Keep one promise you already made. Do not add a new one.",
    close: "Did you keep the faith you already had, or hunt a new feeling?",
    pt: {
      title: "Guarde a fé",
      teach: "O bom combate não se ganha com um humor. Termina-se. Uma carreira tem a última milha. Guardei a fé: uma vida inteira em quatro palavras, e ainda está disponível hoje.",
      keep: "Cumpra uma promessa que você já fez. Não acrescente outra.",
      close: "Você guardou a fé que já tinha, ou caçou um sentimento novo?",
    },
  },
];
